### ISSUE TITLE
Which phone customer is talking about.

### ISSUE THREAD

**Issue by 22shubh22** [tc2n/secohand#11]
We need to give serial number to each phone entry.
This will help us to identify, -> Which phone customer is talking about.
2nd -> With this admin can delete correct phone entry from the database, once the phone is sold.

**Comment by 22shubh22** [comment]
A way to implement

1. A S.No entry will be in the database,
2. S.No of the phone need to be reflected on the UI?
3. When the customer will whatsapp the admin for quering the phone, the S.No of the phone also needs to be shared along way.

**Comment by tc2n** [comment]
https://github.com/tc2n/secohand/commit/5cbcb3da8ffda590edf27886323521e82f879c4f
