### ISSUE TITLE
[SubmitYourPhone] Mark required field with red astrik.

### ISSUE THREAD

**Issue by 22shubh22** [tc2n/secohand#14]
the required field in the form should be in red astrick.

**Comment by tc2n** [comment]
Will it be okay if I mark '*' against the placeholders only, otherwise it'll be hell lot of work.

**Comment by 22shubh22** [comment]
Okay, but without the required fields, the phone information should not be submitted.

**Comment by 22shubh22** [comment]
#19 address it.
