### ISSUE TITLE
[Whatsapp] Whatsapp msg in 'findAPhone'

### ISSUE THREAD

**Issue by 22shubh22** [tc2n/secohand#16]
When a user chats with the admin regarding a mobile to buy, he/she should have to provide the mobile ID.

So, the first auto msg passed in Whatsapp Launcher parameter should be 'Mobile ID: ABCD'.
what do you think?

**Comment by tc2n** [comment]
On the home page how would we know, about which phone is user talking about, so this option is implemented when user clicks on a phone tab.

**Comment by 22shubh22** [comment]
Okay
